- name: Gather LVM facts
  community.general.lvg:
    vg: "{{ vg_name }}"
  register: vg_info

- name: Extend {{ extend_home_lv }} LV
  community.general.lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    size: "{{ extend_home_size }}"
    resizefs: "{{ extend_home_resizefs }}"
  register: lv_extend

- name: Report change
  ansible.builtin.debug:
    msg: "Extended LV {{ lv_name }} in VG {{ vg_name }} to {{ extend_home_size }}"
  when: lv_extend is changed
